name: aztube
description: AzTube Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  http: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  file_picker: ^6.1.1
  just_waveform: ^0.0.5
  receive_intent: ^0.2.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  permission_handler: ^11.0.1
  media_store_plus: ^0.1.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/device_link_qr_overlay.png
