name: aztube
description: AzTube Mobile App
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  http: ^1.1.0
  uuid: ^3.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/device_link_qr_overlay.png
