name: aztube
description: AzTube Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  http: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  just_waveform: ^0.0.5
  receive_intent: ^0.2.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3 
  permission_handler: ^11.0.1
  media_store_plus: ^0.1.3
  path_provider: ^2.1.3
  path: ^1.9.0
  mobile_scanner: ^6.0.1
  device_info_plus: ^11.1.0

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/device_link_qr_overlay.png
