name: Flutter

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - run: flutter pub get
    - run: flutter build appbundle
    - run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/aztube.aab
    - uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: app-bundle
        path: build/app/outputs/bundle/release/aztube.aab
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/app/outputs/bundle/release/aztube.aab
